name: Sync Mangayomi Extensions

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  workflow_dispatch:  # Allows manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Your Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensure full history

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions@users.noreply.github.com"

      - name: Add Upstream Repository
        run: |
          git remote add mangayomi https://github.com/gato404/kegareta-sauces.git || true
          git fetch mangayomi

      - name: Sync JavaScript Folder (Update or Add)
        run: |
          git checkout mangayomi/main -- javascript
          
          # Loop through all files in javascript folder
          for file in $(find javascript -type f); do
            if [[ -f "$file" ]]; then
              # If file exists, check for differences
              if ! git diff --quiet HEAD -- "$file"; then
                echo "Updating: $file"
                git checkout mangayomi/main -- "$file"
              fi
            else
              # If file does not exist, add it
              echo "Adding new file: $file"
              git checkout mangayomi/main -- "$file"
            fi
          done
          
          git add javascript
          git commit -m "Sync: Updated/Added files in JavaScript" || echo "No changes to commit"
          git push origin main

      - name: Sync Dart Folder (Update or Add)
        run: |
          git checkout mangayomi/main -- dart
          
          # Loop through all files in dart folder
          for file in $(find dart -type f); do
            if [[ -f "$file" ]]; then
              # If file exists, check for differences
              if ! git diff --quiet HEAD -- "$file"; then
                echo "Updating: $file"
                git checkout mangayomi/main -- "$file"
              fi
            else
              # If file does not exist, add it
              echo "Adding new file: $file"
              git checkout mangayomi/main -- "$file"
            fi
          done
          
          git add dart
          git commit -m "Sync: Updated/Added files in Dart" || echo "No changes to commit"
          git push origin main
